# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: online阳光-专注于大前端行业领域
subtitle: '一个专注于大前端的技术博客'
indexDesc: 'online阳光是个人开发者的技术内容分享平台,专注于大前端领域,通过技术文章的分析,来对相关的开源框架进行深入的了解,更懂得自己编写的代码,沉淀见解思维'
description: 'online阳光, 专注于大前端行业领域的学习, javascript, css, html, vue, react, android, ios, react-native, grunt, Node.js, webpack, gulp, 小程序, 一个都不能少'
keywords: 'online阳光, zhenggl, koby, 阳光online, javascript, css, html, vue, react, android, ios, react-native, grunt, Node.js, webpack, gulp, 小程序'
author: Genglin Zheng
language: zh-CN
timezone: 'Asia/Shanghai'
email: kbmjj123@gmail.com
userIcon: https://secure.gravatar.com/avatar/40041fb63116f0207c65083f47f32ddb?s=96&d=mm&r=g

jsonContent:
  meta: true
  pages: true
  posts:
    title: true
    date: true
    path: true
    text: true
    raw: false
    content: false
    slug: false
    updated: true
    comments: true
    link: false
    permalink: true
    excerpt: true
    categories: true
    tags: true
    keywords: true


# Content
excerpt_link: 阅读更多
content_max_width: 800px

# Links:
links:
  - svg: ./source/svg/_github.svg
    url: https://www.91temaichang.com
  - svg: ./source/svg/_more.svg
    url: http://weibo.com/sanonz
  - svg: ./source/svg/_twitter.svg
    url: https://twitter.com/sanonze

# Baidu
baidu:
  id: e4027971a230b210f4671f485b33846a

# Miscellaneous
rss: /atom.xml
favicon: /images/favicon.ico

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
#url: https://www.91temaichang
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  diy/**

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: '  '
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 20
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map: 分类
tag_map: 标签

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: miho

# 备案号信息
icp: 粤ICP备14102113号-1

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment

#  以下是github的部署
url: https://www.91temaichang.com

#pwa:
#  manifest:
#    path: /manifest.json
#    body:
#      name: zhenggl
#      short_name: zhenggl
#      lang: zh-CN
#      display: standalone
#      background_color: "#ecedee"
#      theme_color: "#414852"
#      icons:
#        - src: /images/favicon/xin-32.png
#          sizes: 32x32
#          type: image/png
#        - src: /images/favicon/xin-192.png
#          sizes: 192x192
#          type: image/png
#        - src: /images/favicon/xin-512.png
#          sizes: 512x512
#          type: image/png
#  serviceWorker:
#    options:
#      offlineGoogleAnalytics: true

# codepen
codepen:
  src_prefix: 'https://codepen.io/kbmjj123/embed'
  default_tab: html,result
  theme_id: light
  style: 'height: 400px; width: 100%;'

stackblitz:
  style: 'display: inline-block;color: #fff;background-color:#ff8b48;padding: 8px 12px;border-radius: 4px;'

githubEmojis:
  enable: true
  className: github-emoji
  inject: true
  styles:
  customEmojis:

google_ad: true
google_id: true

# 以下是友链
friendLink:
  - title: 技术知识堂
    link: https://www.jhelp.net
  - title: Jason技术流水账
    link: http://tech.jasonsoso.com

# 以下是图片懒加载
lazyload:
  enable: true
  onlypost: true
  isSPA: false
  loadingImg: /images/loading.gif

# 以下是生成网站的
sitemap:
  path: 
    - sitemap.xml
    - sitemap.txt
  template: ./sitemap_template.xml
  template_txt: ./sitemap_template.txt
  rel: false
  tags: true
  categories: true

# 以下是标签云插件的定义
tagcloud:
  enable: true
  documentId: card-tag-cloud